services:

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: meeting_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://meeting_user:meeting_pass@postgres:5432/meeting_db
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  celery:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: meeting_celery
    command: celery -A backend.worker.celery_app worker --loglevel=info
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://meeting_user:meeting_pass@postgres:5432/meeting_db
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: meeting_postgres
    environment:
      POSTGRES_USER: meeting_user
      POSTGRES_PASSWORD: meeting_pass
      POSTGRES_DB: meeting_db
    ports:
      - "5433:5432"   # 5433 only for Windows host access
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: meeting_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data: